{% set name = "medenv" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/medenv-{{ version }}.tar.gz
  sha256: 2c0ce848d7df1e3ebc7ff1aa268aa75a455cd76d4e67e62e1d1d39e3f5ea11c1 

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - netcdf4 >=1.5.8
    - pydap >=3.3.0
    - tqdm >=4.66.1
    - pandas >=2.1.3
    - xarray >=2023.11.0
    - lxml >=4.9.3

test:
  imports:
    - medenv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jeremyfix/medenv
  summary: "Python package to get environmental data from CMEMS, etopo, woa."
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeremyfix
