{% set name = "medenv" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/medenv-{{ version }}.tar.gz
  sha256: 0ad06a50478a5657f83c099d5f428478d737df77d955f7ce393eee81b9bde94c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - netcdf4 >=1.5.8
    - pydap >=3.3.0
    - tqdm >=4.66.1
    - pandas >=2.1.3
    - xarray >=2023.11.0
    - lxml >=4.9.3

test:
  imports:
    - medenv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jeremyfix/medenv
  summary: "Python package to get environmental data from CMEMS, etopo, woa."
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeremyfix
